import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import DragDropProvider from './DragDropProvider'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex-col items-center justify-center `}
      >
        <DragDropProvider>
          <nav className="flex gap-4 justify-center">
            <Link href="/">Домой</Link>
            {/* Prefetched when the link is hovered or enters the viewport */}
            <Link href="/videos">Видео</Link>
            {/* No prefetching */}
            <Link href="/exercises">Упражнения</Link>
          </nav>

          {children}
        </DragDropProvider>


      </body>
    </html>
  );
}
