import type { Metadata } from "next";
import "./globals.css";
import DragDropProvider from './DragDropProvider'
import { AuthProvider } from '@/contexts/AuthContext'
import ProtectedLayout from '@/components/ProtectedLayout'
import Nav from '@/components/Nav'
import { TooltipProvider } from '@/contexts/TooltipContext'
import { WordTooltip } from '@/components/WordTooltip'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex-col items-center justify-center">
        <AuthProvider>
          <ProtectedLayout>
            <TooltipProvider>
              <DragDropProvider>
                <Nav />
                {children}
                <WordTooltip />
              </DragDropProvider>
            </TooltipProvider>
          </ProtectedLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
