import type { Metadata } from "next";
import "./globals.css";
import DragDropProvider from './DragDropProvider'
import { AuthProvider } from '@/contexts/AuthContext'
import ProtectedLayout from '@/components/ProtectedLayout'
import Nav from '@/components/Nav'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex-col items-center justify-center">
        <AuthProvider>
          <ProtectedLayout>
            <DragDropProvider>
              <Nav />
              {children}
            </DragDropProvider>
          </ProtectedLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
